namespace LegendFramework
{
    public enum QUEST_STATE { NORMAL, ADMISSION, COMPLETE }

    public enum WEAPON_TYPE { SWORD, DAGGER, WEAPON_END }
    public enum WEAPON_STATE { NORMAL, RENTAL, LOST }
    public enum WEAPON_GRADE { VERY_HIGH, LEGENDARY, LEGENDARY_TWO, LEGENDARY_LAST }

    public enum ITEM_TYPE { COPPER, IRON, SILVER, ITEM_END }

}
