namespace LegendFramework
{
    public enum QUEST_STATE { NORMAL, ADMISSION, COMPLETE }

    public enum WEAPON_TYPE { GUM, HWAL, CHANG, JIPANGE, DOKKI, WEAPON_END }
    public enum WEAPON_STATE { NORMAL, RENTAL, LOST }
    public enum WEAPON_GRADE { VERY_HIGH, LEGENDARY, LEGENDARY_TWO, LEGENDARY_LAST }

    public enum ITEM_TYPE { TEETH, MEAT, BONE, SKIN, TOENAIL, TREASURE, ITEM_END }

}
